version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python django_project/manage.py makemigrations && python django_project/manage.py migrate && python django_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_project
